language: java
script:
- mvn clean package
deploy: 
provider: heroku
api_key: 
  secure: V6z0JBadudOFRRClgKouCKf6CdqO72psLQB6eG/VlX00lCliJ4BIHn8JaJ/9tIMecAFJBRTa7RXbtzXNzbZvopGupKcdYtXjB7w6sAJQ1YjTdifcwcA6fDano7+bCSAPJ20ODp0QSmLSzOkC9s7HRy/GKg51s0v8ADpJj1jzuBkkZ/6bx2qZEkz5xoXon7MTBorZZ3/a70abjimUXgpDHUbhChvKJkthFDq0YAKWvZs48cA2IIrrMgTrX9jtJIn29x5RddGJ6lnuAdOQY+WXgSoxCaXLeyMD0TygoBBRhRv88YTz72xvTHZS7jqxjDtWEA+GRVzTYzuHfWcdv1EG1SIOQQ8rJrqEKovhlrpT51VlT7ViwLG8UTLDj9oz4Isk8pgBUg92GM0i3or4YpWyzij31IDym9jmh5hWyZ2YNfSKiP6EvsKib3mtKZjpwa+6nG1VRiLZ07EyXmff4ZRFJQxZyqS0iyAPOMd+iQMpz6oy97aKTSp3M3Euci4CUaASpv6lOjt/vlhuLA4IgA3Jvuad/+2nxJr7tDmIDNJ7ieW+t6JYSMzFBsF3b7IY4OLw7Q2jlrNLTkr9dYA33OKz617Bb6IOw6frk9LotMwzshAsZTw+Y4KTCPKm6al5iXAvluQut/9JU3ezPCaFKtjj6rTE9fbGLUNM/GGyj4Kk2xk=
app:
master: team4pi221
on:
repo: mxrph/pi221team4k
